### ISSUE TITLE
Error display value

### ISSUE THREAD

**Issue by gledsoneduardo** [jamesjenner/arcGauge#1]
Hi!

Great job!

But a have a problem (maybe bug).

I have this code:

var gaugepve3 = new ArcGauge({
                id: "gaugenivelpve3",
                value: -7,
                min: -30,
                max: 130,
                startAngle: 4.7,
                arcAngle: 3.18,
                goodMargin: -18,
                width: "100%",
                height: "100%",
                innerRadius: 60,
                outerRadius: 93,
                markerInnerRadius: 95,
                markerOuterRadius: 100,
                goodColor: "#B40404",
                dangerColor: "#B40404",
                markColor: "rgba(150, 150, 150, .8)",
                backgroundColor: "#eee",
                appendTo: "gaugenivelpve3"
});

and result is: -7.000000000000001 

What is it?

Thanks

**Comment by jamesjenner** [comment]
I suspect it's because it's treating the values as percentages as your range is larger than 100. There is an option you can set `valueType`. If you set to `ArcGauge.VALUES_ACTUAL`, this will fix your problem.

**Comment by jamesjenner** [comment]
The problem has now been resolved. textArc.html now includes has examples for negative and positive ranges.

**Comment by jamesjenner** [comment]
fixed.
