### ISSUE TITLE
Value not respect min value

### ISSUE THREAD

**Issue by gledsoneduardo** [jamesjenner/arcGauge#2]
Hi!

I have this code:

var v = new ArcGauge({
    value: -40, 
    minValue: -10,
    maxValue: 100,
    startAngle: 4.7,
    arcAngle: 3.18,
    goodMargin: 5,
    dangerMargin: 20,
    valueType: ArcGauge.VALUES_ACTUAL,
    target: 50,
    width: "100%",
    height: "100%",
    innerRadius: 60,
    outerRadius: 93,
    markerInnerRadius: 95,
    markerOuterRadius: 100,

//    innerRadius: 80,
//    outerRadius: 120,
//    markerInnerRadius: 122,
//    markerOuterRadius: 126,
    goodColor: "rgb(50,200,50)",
    warningColor: "rgb(200,200,50)",
    dangerColor: "rgb(200,50,50)",
    markColor: "rgba(150, 150, 150, .8)",
    backgroundColor: "#eee",
    appendTo: "myGauge"
  })

And the arc plot min than -10.

**Comment by jamesjenner** [comment]
Hi Gledsoneduardo, 

Sorry for not replying sooner, I get too much noise in my notifications, I'll have to sort that out so I can reply in a more timely manor.

I'll have a test of your scenario today and see what happens. I suspect that I have no validation of ranges, I've noticed a defect on my end where if I enter a large range that the gauge only goes to the max, but the target rotates beyond what it should do. I suspect both problems are related.

**Comment by jamesjenner** [comment]
Fixed in version 0.0.2.
